# ─── OpenROAD Installation & Basic Flow Example ──────────────────────────────
# Generated by OpenROAD AI Assistant
# Usage: python run.py --run openroad_example_flow.tcl
# ─────────────────────────────────────────────────────────────────────────────

# ── Step 1: Verify OpenROAD installation ─────────────────────────────────────
# Run in your shell (not Tcl) to confirm version:
# openroad -version

# ── Step 2: Set design parameters ────────────────────────────────────────────
set design_name "my_design"
set tech_file   "sky130"

# ── Step 3: Read the design LEF and Liberty files ────────────────────────────
read_lef  platform/${tech_file}/lef/sky130_fd_sc_hd.tlef
read_lef  platform/${tech_file}/lef/sky130_fd_sc_hd_merged.lef
read_liberty platform/${tech_file}/lib/sky130_fd_sc_hd__tt_025C_1v80.lib

# ── Step 4: Read the synthesized Verilog netlist ─────────────────────────────
read_verilog results/${design_name}.v
link_design  ${design_name}

# ── Step 5: Read timing constraints ──────────────────────────────────────────
read_sdc constraints/${design_name}.sdc

# ── Step 6: Floorplanning ─────────────────────────────────────────────────────
initialize_floorplan \
    -utilization 45 \
    -aspect_ratio 1.0 \
    -core_space 5.0

# ── Step 7: Place power/ground pins and PDN ───────────────────────────────────
source platform/${tech_file}/pdn.tcl

# ── Step 8: Global placement ──────────────────────────────────────────────────
global_placement -timing_driven

# ── Step 9: Estimate parasitics and repair timing ─────────────────────────────
estimate_parasitics -placement
repair_design
repair_timing

# ── Step 10: Detailed placement ───────────────────────────────────────────────
detailed_placement
check_placement -verbose

# ── Step 11: Clock Tree Synthesis (CTS) ───────────────────────────────────────
clock_tree_synthesis
repair_clock_nets

# ── Step 12: Global Routing ───────────────────────────────────────────────────
set_global_routing_layer_adjustment metal2-metal5 0.3
global_route -guide_file results/${design_name}.guide

# ── Step 13: Detailed Routing ─────────────────────────────────────────────────
detailed_route -output_drc results/drc.rpt

# ── Step 14: Final checks and output ──────────────────────────────────────────
estimate_parasitics -global_routing
report_timing
report_design_area
check_antennas -report_file results/antenna.rpt

# Write final outputs
write_def results/${design_name}_final.def
write_gds results/${design_name}_final.gds
